### ISSUE TITLE
[tech debt] write our own css for search

### ISSUE THREAD

**Issue by al63** [CAVaccineInventory/vaccinatethestates#110]
Right now we import mapbox geocoders CSS and then mangle it in main.css to work how we want it to. This is quite brittle and honestly barely even works. We should fix this problem by not importing mapbox's css and instead write it entirely ourselves.

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down/
