### ISSUE TITLE
Maybe revisit bounding box for MTS

### ISSUE THREAD

**Issue by skalnik** [CAVaccineInventory/vaccinatethestates#179]
@eliblock pointed this location out in Discord: ![](https://cdn.discordapp.com/attachments/799197521540022292/837577577887432744/unknown.png)

Our bounding box is pretty big, since we're including all states and territories. I wonder if we can make it a bit better?

For reference, we use https://github.com/CAVaccineInventory/vaccine-feed-ingest/blob/f40525632dc4f9a9b8d6371903020079e0783a9e/vaccine_feed_ingest/utils/validation.py#L19-L28, but this excludes Guam.

It may not be possible to improve, which is fine. But figured I'd capture this, let us re-think or discuss, and can always just close it out if it's not reasonable 😃

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down/
