### ISSUE TITLE
switch to using concordances for credit

### ISSUE THREAD

**Issue by rhkeeler** [CAVaccineInventory/vaccinatethestates#200]
we use vaccinefinder_location_id (&sim) for showing data source right now; we should use concordances -- if a site has a `vaccinefinder_org:` or `vaccinefinder` concordance then the data is from vaccinefinder and so on.

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down/
