### ISSUE TITLE
Integrate real-time appointment availability using getmyvax

### ISSUE THREAD

**Issue by obra** [CAVaccineInventory/vaccinatethestates#270]
http://getmyvax.org/docs/ has docs on the API we'll use to integrate real-time appointment availability into vaccinatethestates.com

We'll use concordances for the getmyvax.org locations, presumably sent through the mapbox tiles we use to render the site to figure out which locations might have availability listed on getmyvax.org. 

Right now, we'd have to pull state by state feeds from getmyvax, but maybe we can sweet-talk them into giving us a query-by-latlon+radius api

**Comment by shajith** [comment]
I finally got around to digging into what this might take. I think this is a rough checklist (assuming per-state querying of getmyvax for now):

- [ ] Getmyvax locations need to be imported into vial and have concordance identifiers that we can use to connect them to their data, in API payloads from them. I wanna say we have done this already, based on [these PRs](https://github.com/CAVaccineInventory/vaccine-feed-ingest/pulls?q=is%3Apr+getmyvax), but it would be nice to get confirmation.
- [ ] Export state abbreviation and getmyvax identifiers to mapbox. I believe this needs a patch [here](https://github.com/CAVaccineInventory/vial/blob/16039120f351e9f4bcf19f8bfc3be2a751dc5c75/vaccinate/api/export_mapbox.py#L63-L76), but I'm still digging. Maybe @simonw knows? Sending down the state seems easy enough, but I'm still figuring out the workflow to update Mapbox tiles after that.
- [ ] Call [GetMyVax API to retrieve availability per state](https://getmyvax.org/docs/#/paths/~1api~1edge~1locations/get) whenever the map changes, to render appointment availability on the page.

I'm gonna try to get the rendering working, maybe with fake data, while I figure out how the rest of the bits work.

(If anyone has more state on the vial-to-vts rendering pipeline here, please chime in!)

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down/
