### ISSUE TITLE
placeholder for "share with..." page

### ISSUE THREAD

**Issue by rhkeeler** [CAVaccineInventory/vaccinatethestates#73]
from Zoelle:
> a page on the site with ways to spread the word, including sample copy, template flyers for sites, and the embed code for our map once we have it (and how to set the zoom)
> it's literally just text and pictures tho

this is a placeholder task, blocked on getting copy and images from @zoelle.

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down/
